version: 2.1

orbs:
  python: circleci/python@2.1.1   # optional, for helpers

jobs:
  python3:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install system deps
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends gfortran liblapack-dev
      - restore_cache:
          keys:
            - v1-pip-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - v1-pip-{{ arch }}-
      - run:
          name: Install python deps
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -U pip
            set -o pipefail; pip install -r requirements.txt | cat
      - save_cache:
          key: v1-pip-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - run:
          name: Show versions
          command: |
            . venv/bin/activate
            pip freeze
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make test

workflows:
  version: 2
  on-commit:
    jobs:
      - python3
  daily:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only: master
    jobs:
      - python3